apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: s4ijemaho-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:d079278f83e39b5a8caee2f7ec7d02a2c08c5ccc@sha256:9ad0e8d72467fc363f3735c348b61f220c3c878e552c75d62c568b3f27491d82
          name: container-image
